---
- hosts: controlplane
  become: true
  tasks:
    - name: Check if metrics server is installed
      command: kubectl get deployment.apps/metrics-server -n kube-system
      register: check_metrics_server
      failed_when: check_metrics_server.rc > 1
      changed_when: check_metrics_server.rc == 1

    - name: Install metrics server
      command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
      when: check_metrics_server.rc == 1
