---
- hosts: workers
  become: true
  tasks:
    - name: Join the node to cluster
      command: sh /tmp/join-command
      args: 
         creates: /etc/kubernetes/kubelet.conf

  handlers:
    - name: docker status
      service: name=docker state=started