---
- become: true
  hosts: all
  tasks:
    - name: Configure node_ip
      set_fact:
        node_ip: "{{ node_ip | default(ansible_default_ipv4.address) }}"

    - debug: var=node_ip

    - name: Get hostname
      set_fact:
        k8s_hostname: "{{ k8s_hostname | default(ansible_hostname) }}"

    - name: Set server hostname 
      ansible.builtin.hostname:
        name: "{{ k8s_hostname }}"

    - name: Check ip address on hosts file
      lineinfile:
        state: absent
        path: "/etc/hosts"
        regexp: "{{ k8s_hostname }}"
      check_mode: true
      changed_when: false # This just makes things look prettier in the logs
      register: check

    - name: Add IP address to /etc/hosts
      lineinfile: 
        dest: /etc/hosts
        line: '{{ node_ip }} {{ k8s_hostname }}'
        state: present
      when: check.found == 0

    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - jq
        - net-tools
        - gnupg-agent
        - software-properties-common
        - nfs-common
